export const DataTransactions = [
    {
        id: 1,
        icons: 'https://cdn3.iconfinder.com/data/icons/inficons/512/apple.png',
        target: 'Apple',
        description: 'Card number user',
        userName: 'Diana',
        date: '16/6/23, 12:40',
        sum: '14.06',
        type: 'credit',
        pending: true,
        status: 'Approved'
    },
    {
        id: 2,
        icons: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTU4hi55_VHjFE17Cfyzkz_2z1DsqyC5VDrQ&usqp=CAU',
        target: 'Payment',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '174.00',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
    {
        id: 3,
        icons: 'https://cdn3.iconfinder.com/data/icons/inficons/512/apple.png',
        target: 'Apple',
        description: 'Card number user',
        userName: 'Diana',
        date: '1/6/23, 12:40',
        sum: '14.06',
        type: 'credit',
        pending: false,
        status: 'Approved'
    },
    {
        id: 4,
        icons: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTU4hi55_VHjFE17Cfyzkz_2z1DsqyC5VDrQ&usqp=CAU',
        target: 'Payment',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '99.71',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
    {
        id: 5,
        icons: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTU4hi55_VHjFE17Cfyzkz_2z1DsqyC5VDrQ&usqp=CAU',
        target: 'Payment',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '73.58',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
    {
        id: 6,
        icons: 'https://cdn3.iconfinder.com/data/icons/inficons/512/apple.png',
        target: 'Apple',
        description: 'Card number user',
        userName: 'Diana',
        date: '13/6/23, 12:40',
        sum: '14.06',
        type: 'credit',
        pending: true,
        status: 'Approved'
    },
    {
        id: 7,
        icons: 'https://play-lh.googleusercontent.com/dbY_2K9PV8YAUYGgDlyHKG2hAT5k9yJ1F1V0sDhu_dO3_HXfNab7XICkXc23f3OgDZZI',
        target: 'IKEA',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '174.00',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
    {
        id: 8,
        icons: 'https://cdn3.iconfinder.com/data/icons/inficons/512/apple.png',
        target: 'Apple',
        description: 'Card number user',
        userName: 'Diana',
        date: '1/6/23, 12:40',
        sum: '14.06',
        type: 'credit',
        pending: false,
        status: 'Approved'
    },
    {
        id: 9,
        icons: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTU4hi55_VHjFE17Cfyzkz_2z1DsqyC5VDrQ&usqp=CAU',
        target: 'Payment',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '99.71',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
    {
        id: 10,
        icons: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTU4hi55_VHjFE17Cfyzkz_2z1DsqyC5VDrQ&usqp=CAU',
        target: 'Payment',
        description: 'From JPMorgan Chase Bank National',
        userName: '',
        date: '22/1/22, 12:40',
        sum: '73.58',
        type: 'payment',
        pending: false,
        status: 'Approved'
    },
]